<?php

namespace ContainerIwVe8Ep;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_FgFUETSService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.fgFUETS' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.fgFUETS'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'mailer' => ['privates', 'mailer.mailer', 'getMailer_MailerService', true],
            'turing' => ['services', 'App\\Controller\\ajax\\TuringController', 'getTuringControllerService', true],
        ], [
            'mailer' => '?',
            'turing' => 'App\\Controller\\ajax\\TuringController',
        ]);
    }
}
