<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerIwVe8Ep\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerIwVe8Ep/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerIwVe8Ep.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerIwVe8Ep\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerIwVe8Ep\App_KernelDevDebugContainer([
    'container.build_hash' => 'IwVe8Ep',
    'container.build_id' => 'ae0eb2a9',
    'container.build_time' => 1635452246,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerIwVe8Ep');
