<?php

// This file has been auto-generated by the Symfony Cache Component.

return [[

'_default' => 0,

], [

0 => [
    'entrypoints' => [
        'base' => [
            'js' => [
                '/build/runtime.js',
                '/build/vendors-node_modules_jquery_dist_jquery_js.js',
                '/build/vendors-node_modules_core-js_internals_export_js-node_modules_core-js_internals_object-create-1a8c68.js',
                '/build/vendors-node_modules_symfony_stimulus-bridge_dist_index_js-node_modules_bootstrap_dist_js_boo-bdcb9b.js',
                '/build/base.js',
            ],
            'css' => [
                '/build/vendors-node_modules_symfony_stimulus-bridge_dist_index_js-node_modules_bootstrap_dist_js_boo-bdcb9b.css',
                '/build/base.css',
            ],
        ],
        'inscription' => [
            'js' => [
                '/build/runtime.js',
                '/build/vendors-node_modules_jquery_dist_jquery_js.js',
                '/build/vendors-node_modules_core-js_internals_export_js-node_modules_core-js_internals_object-create-1a8c68.js',
                '/build/vendors-node_modules_core-js_modules_es_regexp_constructor_js-node_modules_core-js_modules_es-22c80c.js',
                '/build/inscription.js',
            ],
        ],
        'reset_pass' => [
            'js' => [
                '/build/runtime.js',
                '/build/vendors-node_modules_jquery_dist_jquery_js.js',
                '/build/reset_pass.js',
            ],
        ],
    ],
],

]];
